name: HACS Action

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Code
        uses: "actions/checkout@v2"

      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"

      - name: Hassfest Validation
        uses: "home-assistant/actions/hassfest@master"