on:
  push:
    branches:
      - "main"

name: Create Pre Release

jobs:
  build:
    name: Create Pre Release
    if: "startsWith(github.event.head_commit.message, 'dev')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Pre Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.head_commit.message }}
          release_name: ${{ github.event.head_commit.message }}
          body: |
            DEV-release
          draft: false
          prerelease: true
