on:
  push:
    branches:
      - "main"
name: Create Release

jobs:
  build:
    name: Create Release
    if: "startsWith(github.event.head_commit.message, 'v')"    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0                    
      - name: Get commit-messages
        id: get_messages
        run: |
          git log --pretty=format:"%s" $(git describe --tags --abbrev=0 @^)..@ >> /tmp/messages.txt
          cat /tmp/messages.txt
          echo 'MESSAGES<<EOF' >> $GITHUB_ENV
          printf '\+ %b\n' "$(cat /tmp/messages.txt)" >> $GITHUB_ENV
          echo EOF >> $GITHUB_ENV                  
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.head_commit.message }}
          release_name: ${{ github.event.head_commit.message }}
          body: |
            ${{ env.MESSAGES }}
          draft: false
          prerelease: false
